# Generated by Django 3.0.5 on 2020-04-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserActivity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(db_column='start_time', max_length=255)),
                ('end_time', models.CharField(db_column='end_time', max_length=255)),
                ('user_id', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='UserActivity.User')),
            ],
        ),
    ]
