# Generated by Django 3.0.5 on 2020-05-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserActivity', '0004_auto_20200430_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='user_id',
        ),
    ]
